config/routes.rb
CqlTest::Application.routes.draw do

  resources :messages
  controller :messages do
    match 'delete_messages' => :delete_messages
  end

  resources :users
  controller :users do
    match 'delete_users' => :delete_users
    match 'timeline' => :timeline
    match 'follow' => :follow
  end

   root :to => 'users#index'

end

app/models/cassandra.rb
class Cassandra

  require 'cassandra-cql'

  @@db = CassandraCQL::Database.new('127.0.0.1:9160')
  @@db.execute("USE cql_test")

  def self.connect
    @@db.execute("CREATE KEYSPACE cql_test WITH strategy_class='org.apache.cassandra.locator.SimpleStrategy' AND strategy_options:replication_factor=1")
    @@db.execute("USE cql_test")

    @@db.execute("CREATE COLUMNFAMILY users (uid varchar PRIMARY KEY, first_name varchar, last_name varchar, email varchar)" )
    @@db.execute("CREATE INDEX users_id_idx ON users (email)")

    @@db.execute("CREATE COLUMNFAMILY messages (uid varchar PRIMARY KEY, tstamp varchar)" )

    @@db.execute("CREATE COLUMNFAMILY timelines (uid varchar PRIMARY KEY, fidtime varchar, content varchar)" )

    @@db.execute("CREATE COLUMNFAMILY user_count(cid varchar PRIMARY KEY, counters counter) WITH default_validation = CounterColumnType")
    @@db.execute("update user_count set counters = counters + 0 where cid = counters ")

    @@db.execute("CREATE COLUMNFAMILY followers(fid varchar PRIMARY KEY)" )
  end

  def self.drop_keyspace
    @@db.execute("DROP KEYSPACE cql_test")
  end

  def self.delete_column_families
     @@db.execute("DROP COLUMNFAMILY users")
     @@db.execute("DROP COLUMNFAMILY messages")
     @@db.execute("DROP COLUMNFAMILY timelines")
     @@db.execute("DROP COLUMNFAMILY user_count")
     @@db.execute("DROP COLUMNFAMILY message_count")
     @@db.execute("DROP COLUMNFAMILY followers")
     @@db.execute("DROP COLUMNFAMILY following")
  end

end

app/models/image.rb
class Image
	require 'digest'

  def self.get_gravatar email
    hash = Digest::MD5.hexdigest(email.downcase)
    "http://www.gravatar.com/avatar/#{hash}"
  end
end

app/models/message.rb
class Message < Cassandra

  def self.delete_messages
    @@db.execute("TRUNCATE messages")
  end

  def self.delete_message(mid)
    @@db.execute("DELETE FROM messages WHERE mid=?", mid)
  end

  def self.get_messages
    @@db.execute("SELECT * FROM messages")
  end

  def self.get_followers uid
    @@db.execute("SELECT * FROM followers WHERE fid = ?", uid).fetch
  end

  def self.update_message uid, content
    time = Time.now.to_i

    user = User.get_user uid
	  new_json_obj = {"content" => content, "email" => user['email']}.to_json

    @@db.execute("UPDATE messages set #{time} = ? WHERE uid = ?", new_json_obj, uid.to_s)

    follower = @@db.execute("SELECT * FROM followers").fetch
    unless follower.nil?
      follower.to_hash.each do |key, value|
        unless key == "uid"
          json_obj = {"content" => content, "user_id" => uid}.to_json
          @@db.execute("UPDATE timelines set #{time} = ? WHERE uid = ?", json_obj , key)
        end
      end
    end
  end

end

app/models/user.rb
class User < Cassandra

  require 'json'

  def self.get_messages uid
    @@db.execute("SELECT * FROM messages WHERE uid=?", uid).fetch
  end

  def self.get_timeline uid
    @@db.execute("SELECT * FROM timelines WHERE uid=?", uid)
  end

  def self.delete_users
    @@db.execute("TRUNCATE users")
    @@db.execute("update user_count set counters = counters - #{User.count_users} where cid = counters")
  end

  def self.delete_user(uid)
    @@db.execute("DELETE FROM users WHERE uid=?", uid)
  end

  def self.get_users
    @@db.execute("SELECT * FROM users")
  end

  def self.get_user uid
    @@db.execute("SELECT * FROM users WHERE uid = ?", uid).fetch
  end

  def self.count_users
    count = @@db.execute("SELECT counters FROM user_count")
    count.fetch do |c|
      return c[0]
    end
  end

  def self.update_counter(val)
    @@db.execute("update user_count set counters = counters + #{val} where cid = counters")
  end

  def self.update_user first_name, last_name, email
    uid = User.count_users + 1
    @@db.execute("INSERT INTO users (uid, first_name, last_name, email) VALUES (?,?,?,?)", uid, first_name, last_name, email)
    self.update_counter(1)
  end

  def self.follow_user uid, fid
    time = Time.now.to_i

    @@db.execute("Update followers set #{uid.to_s} = ? where fid = ? ", "", fid.to_s)

    messages = User.get_messages fid
    i=0
    messages.to_hash.each do |key, value|
      unless key == "uid"
        i = i + 1
        a = {"content" => JSON.parse(value)['content'], "user_id" => fid.to_s}.to_json
        @@db.execute("Update timelines set #{time + i} = ? where uid = ? ", a, uid)
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @messages = Message.get_messages
  end

  def new
  end

  def create
    Message.update_message params[:uid], params[:content]
    redirect_to messages_path
  end

  def destroy
    Message.delete_message(params[:mid])
    redirect_to messages_path
  end

  def delete_messages
    Message.delete_messages
    redirect_to messages_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  require 'json'

  def index
    @users = User.get_users
  end

  def show
    @user = User.get_user params[:id]
    @messages = User.get_messages params[:id]
  end

  def new
  end

  def create
    @user = User.update_user params[:first_name], params[:last_name], params[:e_mail]
    redirect_to users_path
  end

  def destroy
    User.delete_user(params[:id])
    redirect_to users_path
  end

  def delete_users
    User.delete_users
    redirect_to users_path
  end

  def timeline
    @user = User.get_user params[:id]
    @timeline = User.get_timeline params[:id]
  end

  def follow
    User.follow_user params[:uid], params[:follow]
    redirect_to users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CqlTest</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/messages/index.html.erb
<h1>User List:</h1>
<div id="links">
  <%= link_to "home", users_path %><br/>
  <%= link_to "new message", new_message_path %><br/>
  <%= link_to "delete messages", delete_messages_path, :action => :delete_messages %><br/><br/>
</div>

<% @messages.fetch do |f| %>
  <% f.to_hash.each do |key, value| %>
    <% unless key == "uid" %>
      <div class = "item">
      <div class="image"><%= image_tag(Image.get_gravatar JSON.parse(value)['email'])%></div>
        <%= key %>
        <%= JSON.parse(value)['content'] %><br/>
      </div>
    <%end%>
  <%end%>
<%end%>

app/views/messages/new.html.erb
<h1>Create new Message</h1>

<%= form_tag('/messages') do %>
  <%= text_field_tag 'uid', :uid %>
  <%= text_field_tag 'content', :content %>
  <%= submit_tag 'submit' %>
<%end%>

app/views/messages/show.html.erb
<%= @message.inspect %>

app/views/users/index.html.erb
<h1>User List Cassandra:</h1>
<div id="links">
  <%= link_to "new User", new_user_path %><br/>
  <%= link_to "delete Users", delete_users_path, :action => :delete_users %><br/>
  <%= link_to "create Message", new_message_path %><br/>
  <%= link_to "list Messages", messages_path %>
</div>

<% @users.fetch do |u| %>
  <div class="item">
    <div class="image"><%= image_tag(Image.get_gravatar u['email'])%></div>
    <%= link_to u['first_name'], user_path(u['uid']) %>
    <%= u['last_name'] %>
    <%= link_to "delete", user_path(u['uid']), :method => :delete %><br/>

    <%= form_tag(follow_path) do %>
      <%= hidden_field_tag :uid, u['uid'] %>
      <%= text_field_tag 'follow', :follow %>
      <%= submit_tag 'follow' %>
    <%end%>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Create new User Cassandra:</h1>

<%= form_tag('/users') do %>
  <%= text_field_tag 'first_name', :first_name %><br/>
  <%= text_field_tag 'last_name', :last_name %><br/>
  <%= text_field_tag 'e_mail', :e_mail %><br/>
  <%= submit_tag 'submit' %>
<%end%>

app/views/users/show.html.erb
<div class="item">
  <div class="image"><%= image_tag(Image.get_gravatar @user['email'] )%></div>
  <%= "Userprofil von: #{@user['first_name']} #{@user['last_name']}" %>
</div><br/>

<%= link_to "go to timeline", timeline_path(:id => @user['uid']) %>
<div id="wrapper">
  <%= "Follower ids:" %>
  <%= "TODO" %><br/>

  <%= "Your last messages:" %><br/>
  <% @messages.to_hash.each do |key, value| %>
    <% unless key == "uid" %>
      <div class="item">
        <div class="image"><%= image_tag(Image.get_gravatar @user['email'] )%></div>
        <%=value%><br/>
       </div>
    <%end%>
  <% end %>
</div>

app/views/users/timeline.html.erb
<%= link_to "home", users_path %><br/>

Hallo <%= "#{@user['first_name']}" %><br/><br/>

<div>
<h2>Stream:</h2>
<% @timeline.fetch do |f| %>
  <% f.to_hash.each do |key, value| %>
    <% unless key == "uid" %>
      <div class = "item">
        <%= JSON.parse(value)['content'] %>
      </div>
    <%end%>
  <%end%>
<%end%>